::C:\Windows\system32\cmd.exe /c "start "foo" /b /wait /affinity 0xFFFFFFFFFFFFFFFF /node 0 "E:\VapourSynthR61\VSPipe.exe" -c y4m "E:\BD\LoveLiveSunshine\s2-06.vpy" - | "E:\BD\LoveLiveSunshine\x265.exe" --y4m -D 10 --preset slower --ctu 32 --crf 15.0 --qg-size 16 --tu-inter-depth 3 --tu-intra-depth 3 --max-tu-size 16 --deblock -1:-1 --pbratio 1.2 --cbqpoffs -2 --crqpoffs -2 --no-sao --me 3 --subme 5 --merange 38 --limit-tu 0 --b-intra --no-rect --no-amp --ref 5 --weightb --keyint 240 --min-keyint 1 --bframes 8 --aq-mode 3 --aq-strength 1.00 --rd 5 --psy-rd 2.0 --psy-rdoq 1.6 --vbv-maxrate 40000 --vbv-bufsize 50000 --rdoq-level 1 --no-open-gop --rc-lookahead 80 --scenecut 40 --qcomp 0.70 --no-strong-intra-smoothing --colorprim bt709 --transfer bt709 --colormatrix bt709 --pools + -o "E:\BD\LoveLiveSunshine\s2-06.hevc" -"

::Rename
::ren "E:\BD\LoveLiveSunshine\s2-06.hevc" "E:\BD\LoveLiveSunshine\s2-06-ft.hevc"

::C:\Windows\system32\cmd.exe /c "start "foo" /b /wait /affinity 0xFFFFFFFFFFFFFFFF /node 0 "E:\VapourSynthR61\VSPipe.exe" -c y4m "E:\BD\LoveLiveSunshine\s2-09.vpy" - | "E:\BD\LoveLiveSunshine\x265.exe" --y4m -D 10 --preset slower --ctu 32 --crf 15.0 --qg-size 16 --tu-inter-depth 3 --tu-intra-depth 3 --max-tu-size 16 --deblock -1:-1 --pbratio 1.2 --cbqpoffs -2 --crqpoffs -2 --no-sao --me 3 --subme 5 --merange 38 --limit-tu 0 --b-intra --no-rect --no-amp --ref 5 --weightb --keyint 240 --min-keyint 1 --bframes 8 --aq-mode 3 --aq-strength 1.00 --rd 5 --psy-rd 2.0 --psy-rdoq 1.6 --vbv-maxrate 40000 --vbv-bufsize 50000 --rdoq-level 1 --no-open-gop --rc-lookahead 80 --scenecut 40 --qcomp 0.70 --no-strong-intra-smoothing --colorprim bt709 --transfer bt709 --colormatrix bt709 --pools + -o "E:\BD\LoveLiveSunshine\s2-09.hevc" -"

::C:\Windows\system32\cmd.exe /c "start "foo" /b /wait /affinity 0xFFFFFFFFFFFFFFFF /node 0 "E:\VapourSynthR61\VSPipe.exe" -c y4m "E:\BD\LoveLiveSunshine\s2-11.vpy" - | "E:\BD\LoveLiveSunshine\x265.exe" --y4m -D 10 --preset slower --ctu 32 --crf 15.0 --qg-size 16 --tu-inter-depth 3 --tu-intra-depth 3 --max-tu-size 16 --deblock -1:-1 --pbratio 1.2 --cbqpoffs -2 --crqpoffs -2 --no-sao --me 3 --subme 5 --merange 38 --limit-tu 0 --b-intra --no-rect --no-amp --ref 5 --weightb --keyint 240 --min-keyint 1 --bframes 8 --aq-mode 3 --aq-strength 1.00 --rd 5 --psy-rd 2.0 --psy-rdoq 1.6 --vbv-maxrate 40000 --vbv-bufsize 50000 --rdoq-level 1 --no-open-gop --rc-lookahead 80 --scenecut 40 --qcomp 0.70 --no-strong-intra-smoothing --colorprim bt709 --transfer bt709 --colormatrix bt709 --pools + -o "E:\BD\LoveLiveSunshine\s2-11.hevc" -"

::C:\Windows\system32\cmd.exe /c "start "foo" /b /wait /affinity 0xFFFFFFFFFFFFFFFF /node 0 "E:\VapourSynthR61\VSPipe.exe" -c y4m "E:\BD\LoveLiveSunshine\s2-12.vpy" - | "E:\BD\LoveLiveSunshine\x265.exe" --y4m -D 10 --preset slower --ctu 32 --crf 15.0 --qg-size 16 --tu-inter-depth 3 --tu-intra-depth 3 --max-tu-size 16 --deblock -1:-1 --pbratio 1.2 --cbqpoffs -2 --crqpoffs -2 --no-sao --me 3 --subme 5 --merange 38 --limit-tu 0 --b-intra --no-rect --no-amp --ref 5 --weightb --keyint 240 --min-keyint 1 --bframes 8 --aq-mode 3 --aq-strength 1.00 --rd 5 --psy-rd 2.0 --psy-rdoq 1.6 --vbv-maxrate 40000 --vbv-bufsize 50000 --rdoq-level 1 --no-open-gop --rc-lookahead 80 --scenecut 40 --qcomp 0.70 --no-strong-intra-smoothing --colorprim bt709 --transfer bt709 --colormatrix bt709 --pools + -o "E:\BD\LoveLiveSunshine\s2-12.hevc" -"

::C:\Windows\system32\cmd.exe /c "start "foo" /b /wait /affinity 0xFFFFFFFFFFFFFFFF /node 0 "E:\VapourSynthR61\VSPipe.exe" -c y4m "E:\BD\MV\BDROM\BDMV\STREAM\10.vpy" - | "E:\BD\LoveLiveSunshine\x265.exe" --y4m -D 10 --preset slower --ctu 32 --crf 15.0 --qg-size 32 --tu-inter-depth 4 --tu-intra-depth 4 --max-tu-size 32 --deblock -1:-1 --pbratio 1.2 --cbqpoffs -2 --crqpoffs -2 --no-sao --me 3 --subme 5 --merange 57 --limit-tu 0 --b-intra --rect --amp --ref 5 --weightb --keyint 240 --min-keyint 1 --bframes 16 --aq-mode 3 --aq-strength 0.80 --rd 5 --psy-rd 2.0 --psy-rdoq 1.5 --vbv-maxrate 40000 --vbv-bufsize 50000 --rdoq-level 2 --no-open-gop --rc-lookahead 80 --scenecut 40 --qcomp 0.70 --no-strong-intra-smoothing --rc-grain --pools + -o "E:\BD\MV\BDROM\BDMV\STREAM\10.hevc" -"

:End
echo WORKFINISHED
echo 
pause